on:
  push:


jobs:
  test:
    runs-on: macos-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install buck
        run: |
          curl -Lo $HOME/buck.zst https://github.com/facebook/buck2/releases/download/2024-08-15/buck2-aarch64-apple-darwin.zst
          zstd --decompress $HOME/buck.zst
          chmod +x $HOME/buck

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: df -h
      - name: build nativelink
        run: |
          nix build --out-link $HOME/nativelink github:TraceMachina/nativelink/v0.5.1
      - name: start nativelink
        uses: JarvusInnovations/background-action@v1
        with:
          run: |
            $HOME/nativelink/bin/nativelink nativelink_config.json &
          wait-for: 30s
          wait-on: |
            tcp:127.0.0.1:50061
      - name: Build
        run: $HOME/buck build ...
